version: '3'
services:
  manager:
    build:
        context: ./manager
        dockerfile: "Dockerfile.dev"
    ports:
        - "8000:8000"
    depends_on: 
        - "db"
  db:
    image: "postgres"
    ports: 
        - "5432:5432"
    environment: 
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "db"