version: '3'
services:
  manager:
    build:
        context: .
        dockerfile: "Dockerfile.dev"
    ports:
        - "3001:80"
    depends_on: 
        - "db"
  db:
    image: "postgres"
    ports: 
        - "5432:5432"
    environment: 
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "db"